# Generated by Django 4.1.1 on 2022-09-22 18:53

from django.db import migrations

def create_data(apps, schema_editor):
    LeetCode = apps.get_model('frontend', 'LeetCode')
    LeetCode(name="Two Sum", 
    description="Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.", 
    solution=""
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
