# Generated by Django 4.1.1 on 2022-10-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_leetcode_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="leetcode", name="type",),
        migrations.AddField(
            model_name="leetcode",
            name="dsaType",
            field=models.CharField(default=1, max_length=240, verbose_name="DSA_Type"),
            preserve_default=False,
        ),
    ]
