# Generated by Django 4.1.1 on 2022-10-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0003_remove_leetcode_type_leetcode_dsatype"),
    ]

    operations = [
        migrations.AddField(
            model_name="leetcode",
            name="url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
