# Generated by Django 4.1.1 on 2022-10-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0004_leetcode_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="leetcode",
            name="difficulty",
            field=models.CharField(
                default=1, max_length=240, verbose_name="Difficulty"
            ),
            preserve_default=False,
        ),
    ]
