# Generated by Django 4.1.1 on 2022-10-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leetcode",
            name="type",
            field=models.CharField(default=2, max_length=240, verbose_name="Type"),
            preserve_default=False,
        ),
    ]
